[4-channels]
in_dims = 1
num_blocks_per_stage = 3
stage_dims = [16,32,64]
encoded_dims = 4

[8-channels]
in_dims = 1
num_blocks_per_stage = 3
stage_dims = [16,32,64]
encoded_dims = 8

[12-channels]
in_dims = 1
num_blocks_per_stage = 3
stage_dims = [16,32,64]
encoded_dims = 12

[16-channels]
in_dims = 1
num_blocks_per_stage = 3
stage_dims = [16,32,64]
encoded_dims = 16